name: portal_gun
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  animate_do: ^4.2.0
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  go_router: ^17.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
